services:
  - type: web
    name: imrunning-live
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true
